export const medicalList = [
  'Abdul Malek Ukil Medical College',
  'Armed Forces Medical College',
  'Bangladesh College of Physicians and Surgeons',
  'Cantonment Medical College, Bogra',
  'Cantonment Government Medical Colleges in Bangladesh, Chittagong',
  'Cantonment Medical College, Comilla',
  'Cantonment Medical College, Jessore',
  'Cantonment Medical College, Rangpur',
  'Chittagong Medical College',
  'Comilla Medical College',
  'Cox’s Bazar Medical College',
  'Dhaka Medical College',
  'Dinajpur Medical College',
  'Faridpur Medical College',
  'Gonoshasthaya Samaj Vittik Medical College',
  'Govt. Homeopathic Medical College',
  'Jessore Medical College',
  'Khulna Medical College',
  'Kushtia Medical College (KMC)',
  'MAG Osmani Medical College',
  'Mymensingh Medical College',
  'Pabna Government Medical Colleges in Bangladesh',
  'Rajshahi Medical College',
  'Rangpur Medical College',
  'Satkhira Medical College',
  'Shaheed Suhrawardy Medical College (ShSMC)',
  'Shaheed Ziaur Rahman Medical College',
  'Shahid Syed Nazrul Islam Medical College',
  'Sheikh Sayera Khatun Medical College',
  'Sher-e-Bangla Medical College (SBMC)',
  'Sir Salimullah Medical College',
  'Ad-din Women’s Medical College, Dhaka',
  'Anwer Khan Modern Medical College, Dhaka',
  'Faridpur Homoeopathic Medical College,Faridpur',
  'Bangladesh Medical College',
  'Barind Medical College, Rajshahi',
  'Monno Medical College & Hospital',
  'BGC Trust Medical College, Chittagong',
  'Central Medical College, Comilla',
  'Chottagram Ma-O-Shishu Hospital Medical College',
  'Community Based Medical College (cbmc), Mymensingh',
  'Community Medical College, Dhaka',
  'Dr. Sirajul Islam Medical College, Moghbazar, Dhaka',
  'Delta Medical College, Dhaka',
  'Dhaka National Medical College',
  'Eastern Medical College, Comilla',
  'Enam Medical College, Savar, Dhaka',
  'Sylhet Women’s Medical College, Sylhet',
  'Gazi Medical College, Khulna',
  'Gono Bishwabidyalay, Savar, Dhaka',
  'Green Life Medical College, Dhaka',
  'Holy Family Red Crescent Medical College, Dhaka',
  'Ibrahim Medical College, Dhaka',
  'Ibn Sina Medical College, Dhaka',
  'International Medical College, Gazipur',
  'Jahurul Islam Medical College, Kishoregonj',
  'Jalalabad Ragib-Rabeya Medical College Sylhet',
  'Khawja Yunus Ali Medical College, Sirajganj',
  'Kumudini Medical College, Tangail',
  'Labaid Medical College Dhanmondi, Dhaka (currently not operating)',
  'Mainamoti Medical College & Hospital, Comilla',
  'Maulana Bhasani Medical College',
  'Marks Medical College and Hospital',
  'Medical College for Women and Hospital, Dhaka',
  'Nightingale Medical College, Dhaka',
  'North Bengal Medical College, Sirajganj',
  'North East Medical College, Sylhet',
  'Northern International Medical College, Dhaka',
  'Northern Private Medical College, Rangpur',
  'Popular Medical College & Hospital, Dhaka, Bangladesh.',
  'Prime Medical College, Rangpur',
  'Rangpur Community Medical College, Rangpur',
  'Islami Bank Medical College, Rajshahi',
  'Sahabuddin Medical College and Hospital',
  'Samaj Vittik Medical College, Mirzanagar,',
  'Shahabuddin Medical College, Dhaka',
  'Z. H. Sikder Women’s Medical College',
  'Southern Medical College, Chittagong',
  'Tairunnessa Memorial Medical College, Gazipur',
  'TMSS Medical College, Bogra',
  'University Of Science and Technology Chittagong',
  'Uttara Adhunik Medical College, Dhaka',
  'Saphena Women’s Dental College & Hospital, Malibagh, Dhaka,',
  'Abdul Kuddus Homeopathic Medical College, Kishoreganj',
  'Armed Forces Medical College',
  'Army Medical College Bogra',
  'Army Medical College, Chittagong',
  'Army Medical College Cumilla',
  'Army Medical College, Jessore',
  'Rangpur Army Medical College',
];
